---
title: "Plot ARCHS4"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(jsonlite)
library(ggplot2)
```

Load data.

```{r expr}
expr <- fromJSON("../data/ace2.archs4.json")
```

Check out data.

```{r head_expr}
head(expr)
```

Split `id`.

```{r metadata}
sapply(expr$id, function(x) strsplit(x, split = "\\.")) |>
  as.data.frame() |>
  t() |>
  as.data.frame() -> metadata

cap_first <- function(x){
  s <- strsplit(x, "")[[1]][1]
  return(sub(s, toupper(s), x))
}

row.names(metadata) <- NULL
colnames(metadata) <- c('root', 'system', 'organ', 'tissue')
metadata$tissue <- tolower(metadata$tissue)
metadata$tissue <- sapply(metadata$tissue, cap_first)
head(metadata)
```

Join tables.

```{r data}
data <- cbind(metadata, expr)
head(data)
```

Plot using base R.

```{r plot_base_r, fig.width=12, fig.height=8}
sm <- c('min', 'q1', 'median', 'q3', 'max')
bp_df <- data[, sm]
bp_mat <- t(as.matrix(bp_df))

bp_list <- list(
  stats = matrix(
    bp_mat,
    nrow = 5
  ),
  n = rep(1, ncol(bp_mat)),
  names = data$tissue
)

par(mar = c(10, 5, 1, 1))
bxp(bp_list, show.names = TRUE, las = 2, cex.axis = 0.75)
```

Using ggplot2.

```{r plot_ggplot2, fig.width=12, fig.height=8}
wanted <- c('system', 'tissue', 'min', 'q1', 'median', 'q3', 'max')
data_sub <- data[, wanted]

data_sub <- data_sub[order(data_sub$system), ]
data_sub$tissue <- factor(data_sub$tissue, levels = data_sub$tissue)

ggplot(
  data_sub,
  aes(
    x = tissue,
    ymin = min,
    lower = q1,
    middle = median,
    upper = q3,
    ymax = max,
    fill = system
  )
) +
  geom_boxplot(stat = 'identity') +
  theme_minimal() +
  theme(
    legend.position = 'bottom',
    axis.title.x = element_blank(),
    axis.text.x = element_text(angle = 70, hjust = 1)
  ) +
  labs(y = "Expression")
```