---
title: "Introduction to docstring"
output:
   github_document:
      toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE)
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.path = "img/")

.libPaths('/packages')
my_packages <- c('docstring')

using<-function(...) {
   # https://stackoverflow.com/a/44660688
   libs<-unlist(list(...))
   req<-unlist(lapply(libs,require,character.only=TRUE))
   need<-libs[req==FALSE]
   if(length(need)>0){
      install.packages(need)
   }
}

using(my_packages)
```

## Introduction

[Introduction to docstring](https://cran.r-project.org/web/packages/docstring/vignettes/docstring_intro.html).

```{r load_library}
library(docstring)
```

Square function.

```{r square}
square <- function(x){
    #' Computes the square of the input
    return(x^2)
}
```

Get help.

```{r square_help}
?square
```

Try again.

```{r square_longer_doc}
square <- function(x){
    #' Squares a number
    #'
    #' Provides the square of the input
    #' @param x The value to be squared
    return(x^2)
}

?square
```

Well, doesn't look like it works for me.

## Session info

This document was generated by rendering `r knitr::current_input()` using `rmd_to_md.sh`.

```{r time, echo=FALSE}
Sys.time()
```

Session info.

```{r session_info, echo=FALSE}
sessionInfo()
```
